### ISSUE TITLE
Fix out-of-date proxy-setup's environment overrides

### ISSUE THREAD

**Issue by jim-wang-intel** [edgexfoundry/edgex-compose#11]
In the service `proxy-setup`, the environment section, there are two out-of-date envs:
```yaml
 environment:
      KONGURL_SERVER: kong
      SECRETSERVICE_SERVER: edgex-vault
      SECRETSERVICE_TOKENPATH: /tmp/edgex/secrets/edgex-security-proxy-setup/secrets-token.json
```

Change `SECRETSERVICE_SERVER` to `SECRETSTORE_HOST` and
`SECRETSERVICE_TOKENPATH` to `SECRETSTORE_TOKENPATH`
