### ISSUE TITLE
edgex-proxy-setup is not running in secure mode turned on

### ISSUE THREAD

**Issue by jim-wang-intel** [edgexfoundry/edgex-compose#13]
security service `proxy-setup` is running with environment variable `EDGEX_SECURITY_SECRET_STORE: "false"`, in which it should be running with "true".

```yaml
  proxy-setup:
    environment:
  .......
      EDGEX_SECURITY_SECRET_STORE: "false"
      KONGURL_SERVER: kong
      PROXY_SETUP_HOST: edgex-proxy-setup
  ........
```
