### ISSUE TITLE
Device services still use redis message bus when generating compose with mqtt-bus

### ISSUE THREAD

**Issue by cherrycl** [edgexfoundry/edgex-compose#160]
[Reproduce Steps]
Execute command `make gen mqtt-bus ds-virtual ds-modbus no-secty` under compose-builder directory.

[Actual Result]
Get the services in the compose file.
Only `core-data` used `MQTT Message Bus`.
```
  data:
    container_name: edgex-core-data
    depends_on:
    - consul
    - database
    - metadata
    - mqtt-broker
    environment:
      CLIENTS_CORE_COMMAND_HOST: edgex-core-command
      CLIENTS_CORE_DATA_HOST: edgex-core-data
      CLIENTS_CORE_METADATA_HOST: edgex-core-metadata
      CLIENTS_SUPPORT_NOTIFICATIONS_HOST: edgex-support-notifications
      CLIENTS_SUPPORT_SCHEDULER_HOST: edgex-support-scheduler
      DATABASES_PRIMARY_HOST: edgex-redis
      EDGEX_SECURITY_SECRET_STORE: "false"
      MESSAGEQUEUE_AUTHMODE: none
      MESSAGEQUEUE_HOST: edgex-mqtt-broker
      MESSAGEQUEUE_OPTIONAL_CLIENTID: core-data
      MESSAGEQUEUE_PORT: 1883
      MESSAGEQUEUE_PROTOCOL: tcp
      MESSAGEQUEUE_TYPE: mqtt
      REGISTRY_HOST: edgex-core-consul
      SERVICE_HOST: edgex-core-data
    hostname: edgex-core-data
    image: nexus3.edgexfoundry.org:10004/core-data:latest
    networks:
      edgex-network: {}
    ports:
    - 127.0.0.1:5563:5563/tcp
    - 127.0.0.1:59880:59880/tcp
    read_only: true
    security_opt:
    - no-new-privileges:true
    user: 2002:2001
```

device services still used `redis message bus`.
```
  device-modbus:
    container_name: edgex-device-modbus
    depends_on:
    - consul
    - data
    - metadata
    environment:
      CLIENTS_CORE_COMMAND_HOST: edgex-core-command
      CLIENTS_CORE_DATA_HOST: edgex-core-data
      CLIENTS_CORE_METADATA_HOST: edgex-core-metadata
      CLIENTS_SUPPORT_NOTIFICATIONS_HOST: edgex-support-notifications
      CLIENTS_SUPPORT_SCHEDULER_HOST: edgex-support-scheduler
      DATABASES_PRIMARY_HOST: edgex-redis
      EDGEX_SECURITY_SECRET_STORE: "false"
      MESSAGEQUEUE_HOST: edgex-redis
      REGISTRY_HOST: edgex-core-consul
      SERVICE_HOST: edgex-device-modbus
    hostname: edgex-device-modbus
    image: nexus3.edgexfoundry.org:10004/device-modbus:latest
    networks:
      edgex-network: {}
    ports:
    - 127.0.0.1:59901:59901/tcp
    security_opt:
    - no-new-privileges:true
    user: 2002:2001
  device-virtual:
    container_name: edgex-device-virtual
    depends_on:
    - consul
    - data
    - metadata
    environment:
      CLIENTS_CORE_COMMAND_HOST: edgex-core-command
      CLIENTS_CORE_DATA_HOST: edgex-core-data
      CLIENTS_CORE_METADATA_HOST: edgex-core-metadata
      CLIENTS_SUPPORT_NOTIFICATIONS_HOST: edgex-support-notifications
      CLIENTS_SUPPORT_SCHEDULER_HOST: edgex-support-scheduler
      DATABASES_PRIMARY_HOST: edgex-redis
      EDGEX_SECURITY_SECRET_STORE: "false"
      MESSAGEQUEUE_HOST: edgex-redis
      REGISTRY_HOST: edgex-core-consul
      SERVICE_HOST: edgex-device-virtual
    hostname: edgex-device-virtual
    image: nexus3.edgexfoundry.org:10004/device-virtual:latest
    networks:
      edgex-network: {}
    ports:
    - 127.0.0.1:59900:59900/tcp
    read_only: true
    security_opt:
    - no-new-privileges:true
    user: 2002:2001
```
