### ISSUE TITLE
EdgeX Secure Mode doesn't add secure broker settings

### ISSUE THREAD

**Issue by nyameen** [edgexfoundry/edgex-compose#505]
# 🐞 Bug Report

### Affected Services [**REQUIRED**]

 The issue is located in: MQTT message bus broker

### Is this a regression?

 Unsure about previous versions (3.x or later). Found in v4.0.

### Description and Minimal Reproduction [**REQUIRED**]
When generating a docker compose file with security enabled, the secured MQTT broker file is not added, `add-secure-mqtt-broker.yml`. 

Simply adding  `add-secure-mqtt-broker.yml` to the Makefile will cause failures when using `nanomq` as the broker due to the `mosquitto` binary not being present in the `nanomq` image.

https://github.com/edgexfoundry/edgex-compose/blob/992601bf7f2f73d53359d14b8c9a66356a383a75/compose-builder/Makefile#L866-L869

I'd expect the broker to be configured like so (with authentication):

```yaml
mqtt-broker:
    command:
      - /usr/sbin/mosquitto
      - -c
      - /mosquitto/config/mosquitto.conf
    container_name: edgex-mqtt-broker
    depends_on:
      security-bootstrapper:
        condition: service_started
        required: true
      security-secretstore-setup:
        condition: service_started
        required: true
    entrypoint:
      - /edgex-init/messagebus_wait_install.sh
    environment:
      BROKER_TYPE: mosquitto
      CLIENTS_SECURITY_SECRETSTORE_SETUP_HOST: edgex-security-secretstore-setup
      CONF_DIR: /edgex-init/bootstrap-mosquitto/res
      EDGEX_SECURITY_SECRET_STORE: "true"
      ENTRYPOINT: /docker-entrypoint.sh /usr/sbin/mosquitto  -c  /mosquitto/config/mosquitto.conf
   # ... more configurations
```

## 🔥 Exception or Error

```sh
$ make compose 
```
Generates:
```yaml 
mqtt-broker:
    command:
      - /usr/sbin/mosquitto
      - -c
      - /mosquitto-no-auth.conf
    container_name: edgex-mqtt-broker
    hostname: edgex-mqtt-broker
    image: eclipse-mosquitto:2.0.21
    networks:
      edgex-network: null
    ports:
      - mode: ingress
        host_ip: 127.0.0.1
        target: 1883
        published: "1883"
        protocol: tcp
    read_only: true
    restart: always
    security_opt:
      - no-new-privileges:true
    user: 2002:2001
```

## 🌍  Your Environment
**Deployment Environment:**
Ubuntu 22.04

**EdgeX Version [**REQUIRED**]:** v4.0.0

**Anything else relevant?**
I don't think the `taf` generates the correct docker compose file as well. However, I am unfamiliar with the `taf` system.
